/**
 * Export generation service (FR-8).
 *
 * Produces downloadable plain-text or PDF files containing the checklist and
 * lawyer-prep questions. No LLM call is made — this is a pure formatting
 * service sitting behind the global rate limiter only.
 */
import PDFDocument from 'pdfkit';

/** Minimal event-emitter shape PDFKit documents satisfy (keeps tests mockable). */
export interface PdfStream {
  on(event: 'end', listener: () => void): unknown;
  on(event: 'error', listener: (error: Error) => void): unknown;
}

/**
 * Wait for a PDFKit document to flush, surfacing stream errors as rejections.
 *
 * @param doc - The PDFKit document being written.
 * @returns A Promise that resolves on `end` and rejects on `error`.
 */
export function flushPdf(doc: PdfStream): Promise<void> {
  return new Promise((resolve, reject) => {
    doc.on('end', () => resolve());
    doc.on('error', (error: Error) => reject(error));
  });
}

/**
 * Generate a plain-text export.
 *
 * @param checklist        - Action items.
 * @param lawyerQuestions  - Lawyer-prep questions.
 * @returns A UTF-8 buffer ready to be sent as `text/plain`.
 */
export function generateTxtExport(checklist: string[], lawyerQuestions: string[]): Buffer {
  const lines: string[] = [
    'ClearClause — Legal Document Checklist',
    '=======================================',
    '',
    'Action Items',
    '------------',
    ...checklist.map((item, i) => `${i + 1}. ${item}`),
    '',
    'Questions for Your Lawyer',
    '------------------------',
    ...lawyerQuestions.map((q, i) => `${i + 1}. ${q}`),
    '',
    '---',
    'Generated by ClearClause. This is informational, not legal advice.',
  ];
  return Buffer.from(lines.join('\n'), 'utf-8');
}

/**
 * Generate a PDF export with a simple single-page layout.
 *
 * @param checklist        - Action items.
 * @param lawyerQuestions  - Lawyer-prep questions.
 * @returns A Promise resolving to a PDF buffer.
 */
export async function generatePdfExport(
  checklist: string[],
  lawyerQuestions: string[]
): Promise<Buffer> {
  const chunks: Buffer[] = [];
  const doc = new PDFDocument({ margin: 50 });

  doc.on('data', (chunk: Buffer) => chunks.push(chunk));
  const flushed = flushPdf(doc);

  doc.fontSize(20).font('Helvetica-Bold').text('ClearClause — Legal Document Checklist');
  doc
    .fontSize(10)
    .font('Helvetica')
    .fillColor('#666666')
    .text('Informational only, not legal advice.');
  doc.moveDown(0.5);
  doc.fillColor('#000000');

  doc.fontSize(14).font('Helvetica-Bold').text('Action Items');
  doc.fontSize(10).font('Helvetica');
  for (let i = 0; i < checklist.length; i += 1) {
    doc.text(`${i + 1}. ${checklist[i]}`, { width: 500 });
    doc.moveDown(0.3);
  }

  doc.moveDown(0.5);
  doc.fontSize(14).font('Helvetica-Bold').text('Questions for Your Lawyer');
  doc.fontSize(10).font('Helvetica');
  for (let i = 0; i < lawyerQuestions.length; i += 1) {
    doc.text(`${i + 1}. ${lawyerQuestions[i]}`, { width: 500 });
    doc.moveDown(0.3);
  }

  doc.end();
  await flushed;
  return Buffer.concat(chunks);
}
